name: procan
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib=3.7.1
  - numpy=1.24.2
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - plotly=5.13.1
  - ipykernel=6.21.3
  - black=23.1.0
  - flake8=6.0.0
  - pre-commit=3.1.1
  - xgboost=1.7.4
  - hydra-core=1.3.2
  - wandb=0.14.0
  - python-dotenv=1.0.0
  - imbalanced-learn=0.10.1
  - pip:
      - -e .
      - git+https://github.com/mklasby/ingeniator.git
      - interpret==0.3.2
