SMOKE_TEST: False

wandb:
  name: "${model}_${dataset}_gs${loocv.perform_grid_search}_ss${pipeline.standard_scale}\
    _pt${pipeline.power_transform}_rfecv${pipeline.rfecv}_balanced${loocv.balance_classes}_seed${random_seed}"
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}
  start_method: thread
  dir: ${paths.root}

# Select from xgb, rf, svc
model: rf
# Select from cross_sectional, delta, longitudinal
dataset: cross_sectional
timepoint: 0
n_jobs: -1
random_seed: 42
# Drop na data, may only be False for xgb model
drop_na: False
# Use global + modular interaction data only!
global_only: False

loocv:
  perform_grid_search: True
  scoring: "f1_macro"
  balance_classes: False
  n_samples: null
  single_label_upsample: null
  cv: 5
  save_feature_importance: True
  smoke_test: ${SMOKE_TEST}

pipeline:
  standard_scale: False
  power_transform: False
  rfecv: True
  ignore_features:
    - null

paths:
  root: ${oc.env:BASE_PATH}
  data: ${paths.root}/data/raw_data/t12-updated

labels_dict:
  { 0: "Healthy Controls", 1: "Stage 0", 2: "Stage 1a", 3: "Stage 1b", 4: "Transition" }