program: procan_connectome/main.py
method: grid
metric:
  goal: maximize
  name: accuracy
parameters:
  model:
    values: [rf]
  dataset:
    values: [cross_sectional]
  timepoint:
    values: [0]
  drop_na:
    values: [False]
  random_seed:
    values: [8746, 2078, 42, 12, 32, 4, 8, 23, 98, 1223]
  loocv.balance_classes:
    values: [True, False]
  pipeline.standard_scale:
    values: [True, False]
  pipeline.rfecv:
    values: [True]
  pipeline.power_transform:
    values: [True, False]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
